// app/layout.tsx
import "db/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "db/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="relative min-h-screen">

        {/* Background Gradient + Grid */}
        <svg
          className="absolute inset-0 w-full h-full -z-10"
          width="100%"
          height="100%"
        >
          <defs>
            {/* Linear gradient background */}
            <linearGradient id="bgGradient" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="#FFFFFF" />
              <stop offset="100%" stopColor="#F3F4F6" />
            </linearGradient>

            {/* Grid pattern */}
            <pattern id="grid" width="70" height="70" patternUnits="userSpaceOnUse">
              <path d="M 70 0 L 0 0 0 70" fill="none" stroke="#e0e0e0" strokeWidth="1" />
            </pattern>
          </defs>

          {/* Gradient background */}
          <rect width="100%" height="100%" fill="url(#bgGradient)" />

          {/* Grid overlay */}
          <rect width="100%" height="100%" fill="url(#grid)" />
        </svg>

        {/* Page content */}
        <TRPCReactProvider>
          <div className="relative z-10">{children}</div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
